server {
    listen 80;
    server_name localhost marom-magic.click;

    root /usr/share/nginx/html;
    index index.html;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name localhost marom-magic.click;

    ssl_certificate /etc/nginx/certs/live/marom-magic.click/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/live/marom-magic.click/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location /api/ {
        proxy_pass http://app-e4834c44f0b269573e8ec60188-2058065105.us-east-1.elb.amazonaws.com/api/;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}