# CI workflow for building, scanning, and pushing backend/frontend Docker images.

name: CI - Build, Scan & Push

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    strategy:
      matrix:
        include:
          - name: backend
            repository: maromstream-backend
            dockerfile: Server/MagicStreamServer/Dockerfile
            context: Server/MagicStreamServer
            image_tag: backend

          - name: frontend
            repository: maromstream-frontend
            dockerfile: Client/magic-stream-client/Dockerfile
            context: Client/magic-stream-client
            image_tag: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        run: terraform -chdir=terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform -chdir=terraform init -backend=false

      - name: Terraform Validate
        run: terraform -chdir=terraform validate

      - name: Install TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Run TFLint
        run: |
          cd terraform
          tflint --init
          tflint

      - name: Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./terraform
          framework: terraform
          soft_fail: true

      # Install Trivy CLI
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin
          trivy --version

      # IaC Scan
      - name: Trivy IaC Scan
        run: |
          trivy config ./terraform \
            --severity CRITICAL \
            --exit-code 1

      # Docker Build
      - name: Build Docker image
        run: |
          docker build \
            -t ${{ matrix.repository }}:${{ github.sha }} \
            -f ${{ matrix.dockerfile }} \
            ${{ matrix.context }}

      # Image Scan
      - name: Trivy Image Scan
        run: |
          trivy image \
            --severity CRITICAL \
            --exit-code 1 \
            ${{ matrix.repository }}:${{ github.sha }}

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

          aws ecr get-login-password \
            --region $AWS_REGION | \
            docker login \
            --username AWS \
            --password-stdin \
            $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Push image to ECR
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

          REGISTRY="$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
          IMAGE="$REGISTRY/${{ matrix.repository }}"

          docker tag ${{ matrix.repository }}:${{ github.sha }} $IMAGE:${{ github.sha }}
          docker tag ${{ matrix.repository }}:${{ github.sha }} $IMAGE:${{ matrix.image_tag }}

          docker push $IMAGE:${{ github.sha }}
          docker push $IMAGE:${{ matrix.image_tag }}